export const GAMES = [
  {
    id: "things-in-rings",
    name: "Things in Rings",
    subjects: ["Math", "Logic"],
    softSkills: ["Logical Thinking", "Deduction"],
    pedagogicalTrait: "Venn Diagram Classification",
    researchNote:
      "Forces players to dynamically deduce hidden sorting rules, training rule-based induction and mental flexibility.",
    players: "2-6",
    duration: "15-20 min",
    bggScore: 7.2,
    bggId: "284984",
  },
  {
    id: "dixit",
    name: "Dixit",
    subjects: ["Language Arts", "Vocabulary"],
    softSkills: ["Creativity", "Storytelling", "Empathy"],
    pedagogicalTrait: "Abstract Image Interpretation",
    researchNote:
      "Forces players to interpret and connect unrelated abstract images and words, serving as a powerful exercise for creative writing and metaphor comprehension.",
    players: "3-8",
    duration: "30 min",
    bggScore: 7.2,
    bggId: "39856",
  },
  {
    id: "dobble",
    name: "Dobble (Spot It!)",
    subjects: ["Visual Arts"],
    softSkills: ["Self-Regulation", "Reaction Speed", "Concentration"],
    pedagogicalTrait: "Reveal-and-React Inhibition",
    researchNote:
      "Features dynamic, unpredictable stimuli combined with time-pressured responses. This rapid, rule-based inhibition forces players to control impulses under pressure, acutely improving inhibitory control (even beneficial for children with ADHD).",
    players: "2-8",
    duration: "15 min",
    bggScore: 6.6,
    bggId: "65984",
  },
  {
    id: "ghost-blitz",
    name: "Ghost Blitz",
    subjects: ["Logic"],
    softSkills: ["Self-Regulation", "Reaction Speed", "Logical Thinking"],
    pedagogicalTrait: "Speed Deduction & Impulsive Suppression",
    researchNote:
      "Requires players to quickly process conflicting visual cues (color vs. item) and suppress the impulsive urge to grab the wrong item, sharply training cognitive flexibility.",
    players: "2-8",
    duration: "10-20 min",
    bggScore: 6.8,
    bggId: "83195",
  },
  {
    id: "catan-oil-springs",
    name: "The Settlers of Catan: Oil Springs",
    subjects: ["Social Studies", "Economics", "Environmental Science"],
    softSkills: ["Civic Responsibility", "Critical Thinking"],
    pedagogicalTrait: "Tragedy of the Commons Simulation",
    researchNote:
      "Simulates a highly realistic scenario where players must balance personal/financial growth against the ecological collapse of the entire group ecosystem, fostering tangible civic awareness.",
    players: "3-4",
    duration: "60-90 min",
    bggScore: 7.1,
    bggId: "111619",
  },
];
