const GAMES = [
  {
    "id": "men-at-work",
    "name": "Men at Work",
    "subjects": ["Physics"],
    "softSkills": ["Hand-eye Coordination", "Spatial Perception"],
    "pedagogicalTrait": "Stacking and Balancing",
    "researchNote": "A stacking and balancing game set on a construction site. Players compete to build structures and avoid accidents to earn medals.",
    "players": "2-5",
    "duration": "30-45 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School"],
    "bggId": "261114"
  },
  {
    "id": "junk-art",
    "name": "Junk Art",
    "subjects": ["Physics", "Visual Arts"],
    "softSkills": ["Tacit Understanding", "Strategy", "Dexterity"],
    "pedagogicalTrait": "Irregular Stacking",
    "researchNote": "Uses irregular blocks to build structures, testing the tacit understanding and balance strategy between players.",
    "players": "2-6",
    "duration": "30 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "193042"
  },
  {
    "id": "cake-stack",
    "name": "Cakes",
    "subjects": ["Physics"],
    "softSkills": ["Spatial Perception", "Hand-eye Coordination", "Focus"],
    "pedagogicalTrait": "Paper-based Stacking",
    "researchNote": "A cake-themed stacking game that exercises players' spatial perception and balance through card combinations.",
    "players": "2-4",
    "duration": "15-20 min",
    "minAge": 6,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": ""
  },
  {
    "id": "stick-stack",
    "name": "Stick Stack",
    "subjects": ["Physics", "Logic"],
    "softSkills": ["Dexterity", "Strategy", "Color Matching"],
    "pedagogicalTrait": "Wobbling Base Balancing",
    "researchNote": "A dexterity and strategy game where players place colored sticks to build a tower on a wobbling base.",
    "players": "2-8",
    "duration": "15-30 min",
    "minAge": 8,
    "targetStages": ["Lower Elementary", "Upper Elementary", "Middle School"],
    "bggId": "204734"
  },
  {
    "id": "katamino",
    "name": "Katamino",
    "subjects": ["Math", "Geometry"],
    "softSkills": ["Spatial Awareness", "Problem Solving"],
    "pedagogicalTrait": "3D Modular Spatial Connectivity",
    "researchNote": "Players arrange colored blocks or 3D modules according to challenge cards to meet elimination or path connectivity conditions.",
    "players": "1-2",
    "duration": "10-20 min",
    "minAge": 8,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": "6931"
  },
  {
    "id": "rhino-hero",
    "name": "Rhino Hero",
    "subjects": ["Physics"],
    "softSkills": ["Dexterity", "Fine Motor Skills", "Strategy"],
    "pedagogicalTrait": "Card-Based Stacking",
    "researchNote": "Involves building a skyscraper using wall and roof cards, and achieving victory by strategically moving the rhino.",
    "players": "2-5",
    "duration": "5-15 min",
    "minAge": 5,
    "targetStages": ["Pre-K", "Lower Elementary", "Upper Elementary"],
    "bggId": "91514"
  },
  {
    "id": "yubibo",
    "name": "Yubibo (Finger Balance)",
    "subjects": ["Physical Education"],
    "softSkills": ["Teamwork", "Cooperation", "Fine Motor Skills"],
    "pedagogicalTrait": "Finger Balance Cooperation",
    "researchNote": "A 10-minute party icebreaker testing team cooperation. Players must use their fingers to support a stick and keep a ball balanced without touching other colors.",
    "players": "2-8",
    "duration": "10 min",
    "minAge": 6,
    "targetStages": ["Lower Elementary", "Upper Elementary", "Middle School"],
    "bggId": "425602"
  },
  {
    "id": "sense-series",
    "name": "Sense Series",
    "subjects": ["Art"],
    "softSkills": ["Observation", "Memory"],
    "pedagogicalTrait": "Sensory Measurement",
    "researchNote": "A 3-in-1 combo testing tactile sense, visual dimensional estimation, and color gradient identification mapped to numerical memory.",
    "players": "2-4",
    "duration": "15 min",
    "minAge": 6,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "link": "https://www.gcores.com/articles/189821",
    "bggId": "439332"
  },
  {
    "id": "things-in-rings",
    "name": "Things in Rings",
    "subjects": ["Math", "Logic"],
    "softSkills": ["Logical Thinking", "Deduction", "Imagination"],
    "pedagogicalTrait": "Venn Diagram Classification",
    "researchNote": "A deduction game where players figure out the 'rules' for each ring in a Venn diagram. Online players call it a great brainteaser.",
    "players": "2-6",
    "duration": "15-20 min",
    "minAge": 8,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": "408547"
  },
  {
    "id": "dixit",
    "name": "Dixit",
    "subjects": ["Art", "Language Arts"],
    "softSkills": ["Creativity", "Storytelling", "Empathy", "Vocabulary"],
    "pedagogicalTrait": "Interpreting Abstract Pictures",
    "researchNote": "Players interpret and connect abstract images. Widely praised for beautiful artwork; commonly used as an icebreaker to foster creative thinking.",
    "players": "3-8",
    "duration": "30 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "39856"
  },
  {
    "id": "zingo",
    "name": "Zingo!",
    "subjects": ["Language Arts", "Literacy"],
    "softSkills": ["Reaction Speed", "Focus", "Reading Readiness"],
    "pedagogicalTrait": "Fast-Paced Word Matching",
    "researchNote": "A fast-paced bingo-style game for early readers to match pictures and words. Highly recommended by parents for reading readiness.",
    "players": "2-8",
    "duration": "5-10 min",
    "minAge": 4,
    "targetStages": ["Pre-K", "Lower Elementary"],
    "bggId": "12616"
  },
  {
    "id": "sleeping-queens",
    "name": "Sleeping Queens",
    "subjects": ["Math"],
    "softSkills": ["Basic Addition", "Quick Thinking", "Strategy"],
    "pedagogicalTrait": "Mathematical Imprinting",
    "researchNote": "A whimsical family staple where players wake queens. Great for teaching basic addition in a fun, strategic setting.",
    "players": "2-5",
    "duration": "15-20 min",
    "minAge": 8,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": "17053"
  },
  {
    "id": "left-center-right",
    "name": "LCR (Left Center Right)",
    "subjects": ["Math"],
    "softSkills": ["Directional Sense", "Probability Calculation"],
    "pedagogicalTrait": "Dice Rolling Tension",
    "researchNote": "A fast-paced dice game where chips move left, center, or right. Known for pure simplicity and often played at parties.",
    "players": "3-10",
    "duration": "15-30 min",
    "minAge": 5,
    "targetStages": ["Lower Elementary", "Upper Elementary", "Middle School"],
    "bggId": "3522"
  },
  {
    "id": "clumsy-thief-jr",
    "name": "Clumsy Thief Jr.",
    "subjects": ["Math"],
    "softSkills": ["Mental Math", "Speed", "Set Collection"],
    "pedagogicalTrait": "Arithmetic Sums of 10",
    "researchNote": "A math-based card game imprinting sums of 10 without kids realizing they are practicing math.",
    "players": "2-4",
    "duration": "15 min",
    "minAge": 5,
    "targetStages": ["Pre-K", "Lower Elementary"],
    "bggId": "302676"
  },
  {
    "id": "clumsy-thief",
    "name": "Clumsy Thief",
    "subjects": ["Math"],
    "softSkills": ["Mental Math", "Speed", "Set Collection"],
    "pedagogicalTrait": "Arithmetic Sums of 100",
    "researchNote": "A crazy, fast-paced money-snatching game where players make stacks that equal $100. A step up from the Junior version.",
    "players": "2-6",
    "duration": "15 min",
    "minAge": 8,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": "148660"
  },
  {
    "id": "rummikub",
    "name": "Rummikub",
    "subjects": ["Math", "Logic"],
    "softSkills": ["Pattern Recognition", "Strategic Thinking", "Logical Thinking"],
    "pedagogicalTrait": "Number Grouping and Runs",
    "researchNote": "A timeless tile-based game where players create runs and groups of numbers. Excellent for developing pattern recognition.",
    "players": "2-4",
    "duration": "20-40 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "811"
  },
  {
    "id": "even-stevens-odd",
    "name": "Even Steven's Odd",
    "subjects": ["Math"],
    "softSkills": ["Reaction Speed", "Mental Agility"],
    "pedagogicalTrait": "Frantic Dice Racing",
    "researchNote": "A 'wicked fast' dice-rolling game where players race to complete challenges. Great energy burner for kids.",
    "players": "2-4",
    "duration": "20 min",
    "minAge": 8,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": "143070"
  },
  {
    "id": "froggy-fractions",
    "name": "Froggy Fractions",
    "subjects": ["Math"],
    "softSkills": ["Logic", "Fraction Understanding"],
    "pedagogicalTrait": "Parts-and-Wholes Visuals",
    "researchNote": "An educational game praised for its hands-on approach to teaching the relationship between parts and wholes using frogs.",
    "players": "2-5",
    "duration": "15-20 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School"],
    "bggId": "231650"
  },
  {
    "id": "spinderella",
    "name": "Spinderella",
    "subjects": ["Logic", "Spatial Awareness"],
    "softSkills": ["Spatial Reasoning", "Risk Assessment", "Movement"],
    "pedagogicalTrait": "3D Spatial Movement",
    "researchNote": "Winner of the Kinderspiel des Jahres. Features unique 3D mechanics where spiders try to catch ants, fostering 'mean but fun' interaction.",
    "players": "2-4",
    "duration": "15-20 min",
    "minAge": 6,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": "171129"
  },
  {
    "id": "ubongo-3d",
    "name": "Ubongo 3D",
    "subjects": ["Geometry", "Logic"],
    "softSkills": ["Spatial Awareness", "Mental Rotation", "Real-Time Processing"],
    "pedagogicalTrait": "Real-Time 3D Block Fitting",
    "researchNote": "Highly regarded for its challenging spatial reasoning puzzles where players race to fit 3D blocks into specific shapes.",
    "players": "1-4",
    "duration": "25 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "46396"
  },
  {
    "id": "no-thanks",
    "name": "No Thanks!",
    "subjects": ["Math", "Logic"],
    "softSkills": ["Probability Management", "Risk Assessment"],
    "pedagogicalTrait": "Push Your Luck Evaluation",
    "researchNote": "A simple but deep 'modern classic' card game of chicken about managing chips and knowing when to take high-numbered cards.",
    "players": "3-7",
    "duration": "20 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "12942"
  },
  {
    "id": "heureka",
    "name": "Heureka",
    "subjects": ["Math"],
    "softSkills": ["Strategy", "Deduction", "Logic"],
    "pedagogicalTrait": "Exponent Calculation (Powers of 2)",
    "researchNote": "A tactical, niche indie 'brain-burner' abstract game praised for its deep mathematical calculation using powers of 2.",
    "players": "2-4",
    "duration": "20-30 min",
    "minAge": 10,
    "targetStages": ["Middle School", "High School"],
    "bggId": "446496"
  },
  {
    "id": "shadow-block",
    "name": "Shadow Block",
    "subjects": ["Geometry"],
    "softSkills": ["3D Spatial Reasoning", "Mental Rotation", "Problem Solving"],
    "pedagogicalTrait": "2D-to-3D Reconstruction",
    "researchNote": "Visually satisfying game where players stack physical blocks to reconstruct a 3D structure that must match specific 2D shadows.",
    "players": "1-4",
    "duration": "15-20 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School"],
    "bggId": "262443"
  },
  {
    "id": "acornism",
    "name": "Acornism",
    "subjects": ["Math", "Biology"],
    "softSkills": ["Addition", "Abstract Strategy"],
    "pedagogicalTrait": "Spatial Number Matching",
    "researchNote": "Features cute artwork that masks a surprisingly deep and cutthroat strategic core centered around matching acorn numbers.",
    "players": "2-4",
    "duration": "30-45 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School"],
    "bggId": "415750"
  },
  {
    "id": "planet",
    "name": "My First Planet (Planet)",
    "subjects": ["Science", "Ecology"],
    "softSkills": ["Spatial Awareness", "Systems Thinking"],
    "pedagogicalTrait": "3D Ecosystem Tile Placement",
    "researchNote": "A world-building game praised for its unique 3D components and educational value regarding ecosystems and habitats.",
    "players": "2-4",
    "duration": "30-45 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School"],
    "bggId": "252929"
  },
  {
    "id": "animals-of-the-world",
    "name": "Animals of the World",
    "subjects": ["Biology", "Zoology"],
    "softSkills": ["Knowledge Recall", "Trivia"],
    "pedagogicalTrait": "Habitat Trivia Recognition",
    "researchNote": "A great educational tool for animal enthusiasts to test their knowledge of creatures and their global habitats.",
    "players": "2-6",
    "duration": "30 min",
    "minAge": 8,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": "40993"
  },
  {
    "id": "timeline",
    "name": "Timeline",
    "subjects": ["History", "Humanities"],
    "softSkills": ["Relative Comparison", "Chronological Logic"],
    "pedagogicalTrait": "Chronological Ordering",
    "researchNote": "Often called the 'best trivia game' because players don't need exact dates, just the relative chronological order of historical events.",
    "players": "2-8",
    "duration": "15-20 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "85256"
  },
  {
    "id": "yin-shi-zuo-hua",
    "name": "吟诗作画 (Composing Poems and Painting)",
    "subjects": ["Chinese", "Language Arts"],
    "softSkills": ["Imagination", "Creativity"],
    "pedagogicalTrait": "Poetic Imagery Association",
    "researchNote": "A creative game themed around ancient poetry, stimulating children's interest and imagination in classical literature.",
    "players": "2-8",
    "duration": "20-40 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School"],
    "link": "https://mbd.baidu.com/newspage/data/dtlandingsuper?nid=dt_3587537040077086103&sourceFrom=search_a"
  },
  {
    "id": "very-silly-sentences",
    "name": "Very Silly Sentences",
    "subjects": ["English", "Grammar"],
    "softSkills": ["Vocabulary", "Reading Aloud"],
    "pedagogicalTrait": "Parts of Speech Assembly",
    "researchNote": "A literacy game where players use puzzle pieces to build grammatically correct but funny sentences. Excellent for teaching parts of speech.",
    "players": "2-4",
    "duration": "15 min",
    "minAge": 5,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": "37465"
  },
  {
    "id": "happy-hats",
    "name": "Happy Hats",
    "subjects": ["English", "Phonics"],
    "softSkills": ["Reading Blends", "Word Formation"],
    "pedagogicalTrait": "Phonics and 3-Letter Words",
    "researchNote": "A gentle introduction to phonics where players journey through the alphabet. Very effective for kids starting to blend sounds.",
    "players": "2-4",
    "duration": "15 min",
    "minAge": 4,
    "targetStages": ["Pre-K", "Lower Elementary"],
    "bggId": "354927"
  },
  {
    "id": "tall-tale",
    "name": "Tall Tale",
    "subjects": ["Language Arts", "Drama"],
    "softSkills": ["Storytelling", "Imagination", "Public Speaking"],
    "pedagogicalTrait": "Improvisational Word Association",
    "researchNote": "A storytelling 'creative powerhouse' where players use tokens to create infinite imaginative stories, perfect for public speaking skills.",
    "players": "1-8",
    "duration": "30 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "223501"
  },
  {
    "id": "cooking-up-sentences",
    "name": "Cooking up Sentences",
    "subjects": ["Language Arts", "Grammar"],
    "softSkills": ["Pattern Recognition", "Literacy"],
    "pedagogicalTrait": "Visual Cues for Grammar",
    "researchNote": "A 'recipe' based game recommended by teachers for its clear visual cues to learn nouns, verbs, adjectives, and overall sentence structure.",
    "players": "2-4",
    "duration": "20 min",
    "minAge": 7,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": "35084"
  },
  {
    "id": "taco-cat-goat-cheese-pizza",
    "name": "Taco Cat Goat Cheese Pizza",
    "subjects": ["Physical Education"],
    "softSkills": ["Reaction Speed", "Concentration", "Focus"],
    "pedagogicalTrait": "Audio-Visual Matching under Stress",
    "researchNote": "'Pure chaos in a box.' A high-energy reaction game where players slap the deck when the visual card matches the spoken word.",
    "players": "3-8",
    "duration": "10 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "253664"
  },
  {
    "id": "once-upon-a-time",
    "name": "Once Upon a Time",
    "subjects": ["Language Arts"],
    "softSkills": ["Storytelling", "Imagination", "Vocabulary", "Active Listening"],
    "pedagogicalTrait": "Collaborative Narrative Steering",
    "researchNote": "A collaborative storytelling game where players use cards to guide a fairy tale to their secret ending. Great for creative groups.",
    "players": "2-6",
    "duration": "30 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "1234"
  },
  {
    "id": "duplik",
    "name": "Duplik",
    "subjects": ["Art", "Language Arts"],
    "softSkills": ["Verbal Communication", "Active Listening", "Precision"],
    "pedagogicalTrait": "Auditory Comprehension & Drawing",
    "researchNote": "One player describes an image while others draw it, scoring points based on hidden, hilarious criteria.",
    "players": "3-10",
    "duration": "45 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "22348"
  },
  {
    "id": "set",
    "name": "Set",
    "subjects": ["Logic", "Math"],
    "softSkills": ["Visual Perception", "Pattern Recognition", "Logical Thinking"],
    "pedagogicalTrait": "Attribute Intersection Recognition",
    "researchNote": "A highly addictive 'brain-burner' pattern recognition game where players quickly find combinations of three cards. Often used in math circles.",
    "players": "1-20",
    "duration": "30 min",
    "minAge": 6,
    "targetStages": ["Lower Elementary", "Upper Elementary", "Middle School", "High School"],
    "bggId": "1198"
  },
  {
    "id": "dobble",
    "name": "Dobble (Spot It!)",
    "subjects": ["Visual Arts", "Logic"],
    "softSkills": ["Reaction Speed", "Focus", "Self Regulation", "Inhibitory Control"],
    "pedagogicalTrait": "Reveal-and-React Inhibition",
    "researchNote": "Requires players to process new information fast and suppress impulsive grabs. Acutely improves self-regulation, even in children with ADHD.",
    "players": "2-8",
    "duration": "15 min",
    "minAge": 6,
    "targetStages": ["Lower Elementary", "Upper Elementary", "Middle School"],
    "bggId": "63268"
  },
  {
    "id": "ghost-blitz",
    "name": "Ghost Blitz",
    "subjects": ["Logic"],
    "softSkills": ["Reaction Speed", "Logical Thinking", "Self Regulation"],
    "pedagogicalTrait": "Speed Deduction & Inhibition",
    "researchNote": "A 'speed deduction' reaction game forcing players to race for the correct object based on negative or positive clues. Develops mental agility.",
    "players": "2-8",
    "duration": "10-20 min",
    "minAge": 8,
    "targetStages": ["Lower Elementary", "Upper Elementary", "Middle School"],
    "bggId": "83195"
  },
  {
    "id": "lift-it",
    "name": "Lift It!",
    "subjects": ["Physics"],
    "softSkills": ["Cooperation", "Spatial Awareness", "Dexterity"],
    "pedagogicalTrait": "Crane-Based Construction",
    "researchNote": "A cooperative dexterity game where players must work together to build structures using cranes attached to their heads or hands.",
    "players": "1-8",
    "duration": "15-20 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "132497"
  },
  {
    "id": "cabo",
    "name": "Cabo",
    "subjects": ["Logic"],
    "softSkills": ["Memory", "Bluffing", "Risk Assessment"],
    "pedagogicalTrait": "Information Tracking & Minimization",
    "researchNote": "A memory and bluffing card game where players try to minimize their score. Praised for its '100-point reset' rule.",
    "players": "2-4",
    "duration": "20-45 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "271321"
  },
  {
    "id": "knockout",
    "name": "Knockout",
    "subjects": ["Physics"],
    "softSkills": ["Fine Motor Skills", "Spatial Awareness"],
    "pedagogicalTrait": "Precision Extraction",
    "researchNote": "A physical dexterity game where players use a 'rammer hammer' to knock blocks out of a wall. A huge hit for its 'destructive' fun.",
    "players": "2-4",
    "duration": "15 min",
    "minAge": 5,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": "7334"
  },
  {
    "id": "toddles-bobbles",
    "name": "Toddles-Bobbles",
    "subjects": ["Language Arts"],
    "softSkills": ["Memory", "Naming", "Creativity"],
    "pedagogicalTrait": "Abstract Face Association",
    "researchNote": "A hilarious and challenging memory game where players give silly names to abstract characters and must remember them upon reappearance.",
    "players": "2-6",
    "duration": "15 min",
    "minAge": 5,
    "targetStages": ["Lower Elementary", "Upper Elementary", "Middle School"],
    "bggId": "191895"
  },
  {
    "id": "foxy",
    "name": "Foxy",
    "subjects": ["Math"],
    "softSkills": ["Observation", "Working Memory", "Estimation"],
    "pedagogicalTrait": "Cumulative Frequency Betting",
    "researchNote": "A surprisingly deep 'clever twist' on memory games where players observe and bet on how many specific animals they've seen previously.",
    "players": "2-4",
    "duration": "15 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School"],
    "bggId": "359318"
  },
  {
    "id": "cheating-moth",
    "name": "Cheating Moth",
    "subjects": ["Social Studies"],
    "softSkills": ["Bluffing", "Reaction Speed", "Concentration"],
    "pedagogicalTrait": "Rule-Breaking & Deception",
    "researchNote": "Silly, chaotic fun where cheating is not only allowed but required to win, forcing players to read the table and deceive a designated Guard.",
    "players": "3-5",
    "duration": "20 min",
    "minAge": 7,
    "targetStages": ["Lower Elementary", "Upper Elementary", "Middle School"],
    "bggId": "105593"
  },
  {
    "id": "moos-code",
    "name": "Moo's Code",
    "subjects": ["Music", "Language Arts"],
    "softSkills": ["Rhythm Matching", "Auditory Memory"],
    "pedagogicalTrait": "Auditory Communication",
    "researchNote": "A listening and memory game where players 'moo' in rhythm to communicate ingredients. Great for breaking people out of their shells.",
    "players": "2-4",
    "duration": "15 min",
    "minAge": 6,
    "targetStages": ["Lower Elementary", "Upper Elementary", "Middle School"],
    "bggId": "126771"
  },
  {
    "id": "chicken-cha-cha-cha",
    "name": "Chicken Cha Cha Cha",
    "subjects": ["Logic"],
    "softSkills": ["Memory", "Path Planning"],
    "pedagogicalTrait": "Memory-Based Racing",
    "researchNote": "Often cited as one of the best memory games for children, where chickens try to 'pluck' each other's feathers by remembering hidden tiles.",
    "players": "2-4",
    "duration": "20-30 min",
    "minAge": 4,
    "targetStages": ["Pre-K", "Lower Elementary"],
    "bggId": "3570"
  },
  {
    "id": "pixblocks",
    "name": "PixBlocks",
    "subjects": ["Computer Science", "Logic"],
    "softSkills": ["Sequential Thinking", "If-Then Logic"],
    "pedagogicalTrait": "Screenless Programming Fundamentals",
    "researchNote": "A fantastic educational tool that introduces the fundamentals of programming and if-then logic through grid movement without a screen.",
    "players": "1-4",
    "duration": "20 min",
    "minAge": 7,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": "319980"
  },
  {
    "id": "break-the-cube",
    "name": "Break the Cube",
    "subjects": ["Geometry", "Logic"],
    "softSkills": ["Spatial Awareness", "Deduction"],
    "pedagogicalTrait": "3D Shape Deduction",
    "researchNote": "A simple, neat 3D deduction game where players try to figure out the hidden shape of their opponent's blocks.",
    "players": "2",
    "duration": "15 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "354669"
  },
  {
    "id": "cockroach-poker",
    "name": "Cockroach Poker",
    "subjects": ["Psychology", "Social Studies"],
    "softSkills": ["Deception", "Bluffing", "Reading People"],
    "pedagogicalTrait": "Targeted Set Collection & Bluffing",
    "researchNote": "A tense, stressful, but fun bluffing game where players try to foist 'pest' cards onto opponents. Heavy emphasis on reading people.",
    "players": "2-6",
    "duration": "15-25 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "11971"
  },
  {
    "id": "feelinks",
    "name": "Feelinks",
    "subjects": ["Psychology", "Health/Wellness"],
    "softSkills": ["Empathy", "Social Emotional Learning", "Communication"],
    "pedagogicalTrait": "Situation-Emotion Mapping",
    "researchNote": "A game of empathy where players guess how others would feel in various situations, sparking meaningful conversations about emotions.",
    "players": "2-8",
    "duration": "30 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "181363"
  },
  {
    "id": "24-hour-doctor",
    "name": "24 小时医生 (24-Hour Doctor)",
    "subjects": ["Science", "Medical Knowledge"],
    "softSkills": ["Cooperation", "Time Management", "Prioritization", "Critical Thinking"],
    "pedagogicalTrait": "Real-Time Emergency Simulation",
    "researchNote": "A cooperative educational board game simulating a doctor's career, teaching first-aid knowledge and conveying the urgency of diagnosing and treating patients.",
    "players": "2-4",
    "duration": "45-60 min",
    "minAge": 10,
    "targetStages": ["Middle School", "High School"],
    "link": "https://baijiahao.baidu.com/s?id=1846661186153622172&wfr=spider&for=pc"
  },
  {
    "id": "robot-turtles",
    "name": "Robot Turtles",
    "subjects": ["Computer Science", "Logic"],
    "softSkills": ["Sequential Thinking", "Problem Solving"],
    "pedagogicalTrait": "Basic Coding for Preschoolers",
    "researchNote": "The gold standard for teaching coding to young children. Introduces logic and pseudo-programming using cards to navigate a board.",
    "players": "2-5",
    "duration": "15-20 min",
    "minAge": 4,
    "targetStages": ["Pre-K", "Lower Elementary"],
    "bggId": "147370"
  },
  {
    "id": "kayanak",
    "name": "Kayanak",
    "subjects": ["Physics"],
    "softSkills": ["Fine Motor Skills", "Probability", "Action Coordination"],
    "pedagogicalTrait": "Tactile Membrane Piercing",
    "researchNote": "A 'freakishly fun' fishing game where the tactile experience of physically punching holes in paper 'ice' to catch magnetic fish is a huge hit.",
    "players": "2-4",
    "duration": "15 min",
    "minAge": 4,
    "targetStages": ["Pre-K", "Lower Elementary"],
    "bggId": "4493"
  },
  {
    "id": "grab-your-breakfast",
    "name": "Grab Your Breakfast",
    "subjects": ["Health/Wellness"],
    "softSkills": ["Collection Strategy"],
    "pedagogicalTrait": "Light Drafting",
    "researchNote": "A family light drafting game about grabbing the heartiest breakfast possible.",
    "players": "2-4",
    "duration": "20-30 min",
    "minAge": 6,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": "360913"
  },
  {
    "id": "catan-oil-springs",
    "name": "Catan: Oil Springs",
    "subjects": ["Economics", "Environmental Science"],
    "softSkills": ["Resource Management", "Civic Responsibility", "Negotiation", "Critical Thinking"],
    "pedagogicalTrait": "Tragedy of the Commons Simulation",
    "researchNote": "A scenario simulating the use of oil as a powerful resource, forcing players to balance personal financial gain against the collective survival of the board.",
    "players": "3-4",
    "duration": "60 min",
    "minAge": 10,
    "targetStages": ["Middle School", "High School"],
    "bggId": "110794"
  },
  {
    "id": "forbidden-island",
    "name": "Forbidden Island",
    "subjects": ["Logic", "Environmental Science"],
    "softSkills": ["Self Regulation", "Teamwork", "Panic Management", "Critical Thinking"],
    "pedagogicalTrait": "Unpredictable Event/Simulation",
    "researchNote": "Players must regulate their panic and adapt strategy to survive unpredictable outside simulation events, like parts of the board permanently sinking.",
    "players": "2-4",
    "duration": "30 min",
    "minAge": 10,
    "targetStages": ["Upper Elementary", "Middle School"],
    "bggId": "65244"
  },
  {
    "id": "exploding-kittens",
    "name": "Exploding Kittens",
    "subjects": ["Math", "Logic"],
    "softSkills": ["Frustration Management", "Risk Assessment"],
    "pedagogicalTrait": "Push Your Luck & Threat Mitigation",
    "researchNote": "Requires managing frustration and utilizing defuse cards strategically when uncontrollable event cards are drawn.",
    "players": "2-5",
    "duration": "15 min",
    "minAge": 7,
    "targetStages": ["Lower Elementary", "Upper Elementary", "Middle School"],
    "bggId": "172225"
  },
  {
    "id": "jenga",
    "name": "Jenga",
    "subjects": ["Physics"],
    "softSkills": ["Stress Relief", "Fine Motor Skills"],
    "pedagogicalTrait": "Tension and Release Mechanics",
    "researchNote": "Noted as a stressbuster where the falling tower generates laughter, reducing heart rate and blood pressure in the short term.",
    "players": "2-8",
    "duration": "15 min",
    "minAge": 6,
    "targetStages": ["Lower Elementary", "Upper Elementary", "Middle School", "High School"],
    "bggId": "2452"
  },
  {
    "id": "anomia",
    "name": "Anomia",
    "subjects": ["Language Arts", "General Knowledge"],
    "softSkills": ["Mental Agility", "Rapid Processing", "Self Regulation"],
    "pedagogicalTrait": "Time-Pressured Pattern Matching",
    "researchNote": "Requires rapid processing and mental agility under extreme time pressure. Players must quickly blurt out category examples when symbols match.",
    "players": "3-6",
    "duration": "20 min",
    "minAge": 10,
    "targetStages": ["Middle School", "High School"],
    "bggId": "67877"
  },
  {
    "id": "rorys-story-cubes",
    "name": "Rory's Story Cubes",
    "subjects": ["Language Arts", "Art"],
    "softSkills": ["Creativity", "Storytelling", "Improvisation"],
    "pedagogicalTrait": "Abstract Icon Association",
    "researchNote": "Players roll 9 dice featuring completely abstract icons and must instantly weave them together into a single, cohesive story.",
    "players": "1-12",
    "duration": "10-15 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School", "High School"],
    "bggId": "20545"
  },
  {
    "id": "snake-oil",
    "name": "Snake Oil",
    "subjects": ["Language Arts", "Public Speaking"],
    "softSkills": ["Creativity", "Persuasion", "Improvisation"],
    "pedagogicalTrait": "Random Word Combination Pitching",
    "researchNote": "Players combine unrelated word cards to invent wacky products and creatively pitch them to a customer persona, training improvisation.",
    "players": "3-10",
    "duration": "20-30 min",
    "minAge": 10,
    "targetStages": ["Middle School", "High School"],
    "bggId": "113289"
  },
  {
    "id": "global-warming",
    "name": "Global Warming",
    "subjects": ["Science", "Ecology"],
    "softSkills": ["Civic Responsibility", "Accountability"],
    "pedagogicalTrait": "Physical Carbon Emission Tracking",
    "researchNote": "Uses tangible 'train miniatures' to track personal carbon emissions, which makes players feel actively accountable to the group to prevent climate disaster.",
    "players": "2-4",
    "duration": "45 min",
    "minAge": 10,
    "targetStages": ["Middle School", "High School"],
    "bggId": "83468"
  },
  {
    "id": "ecosystem",
    "name": "Ecosystem(2019)",
    "subjects": ["Science", "Biology", "Ecology"],
    "softSkills": ["Environmental Accountability", "Systems Thinking", "Critical Thinking"],
    "pedagogicalTrait": "Simulated Food Web Balancing",
    "researchNote": "Simulates how prioritizing one animal might cause the rest of the environmental grid to fail, enforcing accountability to the entire ecosystem.",
    "players": "2-6",
    "duration": "20 min",
    "minAge": 10,
    "targetStages": ["Upper Elementary", "Middle School"],
    "bggId": "271519"
  },
  {
    "id": "keep-cool",
    "name": "Keep Cool",
    "subjects": ["Science", "Economics"],
    "softSkills": ["Negotiation", "Global Perspective", "Critical Thinking"],
    "pedagogicalTrait": "Climate Negotiation Simulation",
    "researchNote": "Provides participants with a clear, top-down perspective on how different global countries interact and how human actions directly affect climate systems.",
    "players": "3-6",
    "duration": "60-120 min",
    "minAge": 12,
    "targetStages": ["Middle School", "High School"],
    "bggId": "14698"
  },
  {
    "id": "photosynthesis",
    "name": "Photosynthesis",
    "subjects": ["Science", "Biology"],
    "softSkills": ["Critical Thinking", "Change in Perspective", "Spatial Reasoning"],
    "pedagogicalTrait": "Top-Down Canopy Simulation",
    "researchNote": "Provides a highly visual, top-down perspective of how growing a tree casts shadows that immediately restrict the sunlight resources of others.",
    "players": "2-4",
    "duration": "30 min",
    "minAge": 8,
    "targetStages": ["Upper Elementary", "Middle School"],
    "bggId": "218603"
  },
  {
    "id": "similo-animals",
    "name": "Similo: Animals",
    "subjects": ["Biology", "Logic"],
    "softSkills": ["Deduction", "Perspective Taking", "Critical Thinking"],
    "pedagogicalTrait": "Attribute Intersection Deduction",
    "researchNote": "Forces a rapid change in perspective, making players think critically about how different environmental traits intersect to identify a secret animal.",
    "players": "2-8",
    "duration": "10-15 min",
    "minAge": 7,
    "targetStages": ["Lower Elementary", "Upper Elementary"],
    "bggId": "268620"
  },
  {
    "id": "terraforming-mars",
    "name": "Terraforming Mars",
    "subjects": ["Science", "Ecology"],
    "softSkills": ["Systems Thinking", "Long-term Planning"],
    "pedagogicalTrait": "Global Parameter Manipulation",
    "researchNote": "Simulates the complex interaction between temperature, oxygen, and ocean coverage, showing how one player's action shifts global parameters for everyone.",
    "players": "1-5",
    "duration": "120 min",
    "minAge": 12,
    "targetStages": ["Middle School", "High School"],
    "bggId": "167791"
  },
  {
    "id": "daybreak",
    "name": "Daybreak",
    "subjects": ["Science", "Environmental Science", "Social Studies"],
    "softSkills": ["Cooperation", "Systems Thinking", "Critical Thinking"],
    "pedagogicalTrait": "Cooperative Climate Action Simulation",
    "researchNote": "A co-operative game about climate action where each player controls a world power, deploying policies and technologies to dismantle global heating and build resilient societies. Challenge cards support differentiated difficulty for classroom play.",
    "players": "1-4",
    "duration": "60-90 min",
    "minAge": 10,
    "targetStages": ["Middle School", "High School"],
    "bggId": "334986"
  }
];
