#!/usr/bin/env python3
"""Map games to PDF section titles for text-search navigation in pdf-viewer.html."""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

import fitz

ROOT = Path(__file__).resolve().parents[1]
PDF_PATH = ROOT / "assets" / "Final_Board_Game_Report_V3.pdf"
GAMES_DATA = ROOT / "gamesData.js"
ANCHORS_JS = ROOT / "pdf viewer" / "gamePdfAnchors.js"
REPORT_JSON = ROOT / "scripts" / "pdf-anchor-report.json"


def norm(text: str) -> str:
    text = text.lower().strip()
    text = text.replace("\u2019", "'").replace("\u2018", "'")
    return re.sub(r"\s+", " ", text)


def load_games() -> list[dict]:
    content = GAMES_DATA.read_text(encoding="utf-8")
    match = re.search(r"const GAMES = (\[.*\]);", content, re.DOTALL)
    if not match:
        raise SystemExit("Could not parse GAMES from gamesData.js")
    return json.loads(match.group(1))


def search_patterns(name: str) -> list[str]:
    patterns = [name]
    if "(" in name:
        patterns.append(name.split("(")[0].strip())
        paren = re.search(r"\(([^)]+)\)", name)
        if paren:
            patterns.append(paren.group(1).strip())
    if "/" in name:
        patterns.extend(part.strip() for part in name.split("/"))
    return patterns


def find_pdf_title_positions(doc: fitz.Document) -> dict[str, list[dict]]:
    positions: dict[str, list[dict]] = {}
    for page_num in range(doc.page_count):
        page = doc[page_num]
        blocks = page.get_text("dict")["blocks"]
        lines: list[tuple[str, float, float]] = []
        for block in blocks:
            if block.get("type") != 0:
                continue
            for line in block["lines"]:
                text = "".join(span["text"] for span in line["spans"]).strip()
                if not text:
                    continue
                y0 = line["bbox"][1]
                pdf_y = page.rect.height - y0
                lines.append((text, y0, pdf_y))

        for index, (text, y0, pdf_y) in enumerate(lines):
            if text != "Description" or index == 0:
                continue
            title, title_y0, title_pdf_y = lines[index - 1]
            if title in ("Visuals (Components & Gameplay)", "Community Comments"):
                continue
            positions.setdefault(norm(title), []).append(
                {
                    "title": title,
                    "page": page_num,
                    "y0": title_y0,
                    "pdf_y": title_pdf_y,
                }
            )
    return positions


def match_games(games: list[dict], positions: dict[str, list[dict]]) -> tuple[list[dict], list[dict]]:
    matched: list[dict] = []
    unmatched: list[dict] = []

    for game in games:
        hit = None
        pdf_title = game.get("detailPdfTitle")
        if pdf_title:
            key = norm(pdf_title)
            if key in positions:
                hit = {**positions[key][0], "matched_via": pdf_title}

        if not hit:
            for pattern in search_patterns(game["name"]):
                key = norm(pattern)
                if key in positions:
                    hit = {**positions[key][0], "matched_via": pattern}
                    break

        if hit:
            matched.append(
                {
                    "id": game["id"],
                    "name": game["name"],
                    "pdf_title": hit["title"],
                    "page": hit["page"],
                    "page_display": hit["page"] + 1,
                    "pdf_y": hit["pdf_y"],
                }
            )
        else:
            unmatched.append({"id": game["id"], "name": game["name"]})

    return matched, unmatched


def write_anchors_js(matches: list[dict]) -> None:
    entries = sorted(matches, key=lambda match: match["id"])
    body = ",\n  ".join(
        f'"{match["id"]}": {{ search: {json.dumps(match["pdf_title"])}, page: {match["page_display"]} }}'
        for match in entries
    )
    ANCHORS_JS.write_text(
        "/** Auto-generated by scripts/add-pdf-anchors.py — do not edit by hand. */\n"
        f'const GAME_DETAIL_PDF = "./assets/Final_Board_Game_Report_V3.pdf";\n'
        f"const GAME_PDF_ANCHORS = {{\n  {body}\n}};\n",
        encoding="utf-8",
    )


def main() -> int:
    if not PDF_PATH.exists():
        print(f"Missing PDF: {PDF_PATH}", file=sys.stderr)
        return 1

    games = load_games()
    doc = fitz.open(PDF_PATH)
    positions = find_pdf_title_positions(doc)
    doc.close()

    matched, unmatched = match_games(games, positions)
    write_anchors_js(matched)

    report = {
        "pdf": str(PDF_PATH.relative_to(ROOT)),
        "matched": len(matched),
        "unmatched": unmatched,
        "matches": matched,
    }
    REPORT_JSON.write_text(json.dumps(report, indent=2), encoding="utf-8")

    print(f"PDF text matches: {len(matched)}")
    print(f"No PDF section: {len(unmatched)}")
    if unmatched:
        for item in unmatched:
            print(f"  - {item['id']}: {item['name']}")
    print(f"Wrote {ANCHORS_JS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
