#!/usr/bin/env python3
"""Map games to Word guide section titles for text-search navigation in guide-viewer.html."""

from __future__ import annotations

import json
import re
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
DOCX_PATH = ROOT / "assets" / "Final_Board_Game_Report_V3.docx"
GAMES_DATA = ROOT / "gamesData.js"
ANCHORS_JS = ROOT / "doc viewer" / "gamePdfAnchors.js"
REPORT_PATH = ROOT / "scripts" / "pdf-anchor-report.json"

W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
SKIP_TITLES = {
    "Visuals (Components & Gameplay)",
    "Visuals (Components C Gameplay)",
    "Community Comments",
}


def norm(text: str) -> str:
    text = text.lower().strip()
    text = text.replace("\u2019", "'").replace("\u2018", "'")
    return re.sub(r"\s+", " ", text)


def load_games() -> list[dict]:
    content = GAMES_DATA.read_text(encoding="utf-8")
    match = re.search(r"const GAMES = (\[.*\]);", content, re.DOTALL)
    if not match:
        raise SystemExit("Could not parse GAMES from gamesData.js")
    return json.loads(match.group(1))


def search_patterns(name: str) -> list[str]:
    patterns = [name]
    if "(" in name:
        patterns.append(name.split("(")[0].strip())
        paren = re.search(r"\(([^)]+)\)", name)
        if paren:
            patterns.append(paren.group(1).strip())
    if "/" in name:
        patterns.extend(part.strip() for part in name.split("/"))
    return patterns


def read_docx_paragraphs(docx_path: Path) -> list[str]:
    with zipfile.ZipFile(docx_path) as archive:
        root = ET.fromstring(archive.read("word/document.xml"))

    paragraphs: list[str] = []
    for paragraph in root.findall(f".//{{{W_NS}}}p"):
        text = "".join(node.text or "" for node in paragraph.findall(f".//{{{W_NS}}}t")).strip()
        if text:
            paragraphs.append(text)
    return paragraphs


def find_guide_title_positions(paragraphs: list[str]) -> dict[str, list[dict]]:
    positions: dict[str, list[dict]] = {}
    section = 0

    for index, text in enumerate(paragraphs):
        if text != "Description" or index == 0:
            continue

        title = paragraphs[index - 1]
        if title in SKIP_TITLES:
            continue

        section += 1
        positions.setdefault(norm(title), []).append(
            {
                "title": title,
                "section": section,
                "paragraph_index": index - 1,
            }
        )

    return positions


def match_games(
    games: list[dict], positions: dict[str, list[dict]]
) -> tuple[list[dict], list[dict]]:
    matched: list[dict] = []
    unmatched: list[dict] = []

    for game in games:
        hit = None
        guide_title = game.get("detailPdfTitle") or game.get("detailGuideTitle")
        if guide_title:
            key = norm(guide_title)
            if key in positions:
                hit = {**positions[key][0], "matched_via": guide_title}

        if not hit:
            for pattern in search_patterns(game["name"]):
                key = norm(pattern)
                if key in positions:
                    hit = {**positions[key][0], "matched_via": pattern}
                    break

        if hit:
            matched.append(
                {
                    "id": game["id"],
                    "name": game["name"],
                    "guide_title": hit["title"],
                    "section": hit["section"],
                    "paragraph_index": hit["paragraph_index"],
                }
            )
        else:
            unmatched.append({"id": game["id"], "name": game["name"]})

    return matched, unmatched


def write_anchors_js(matches: list[dict]) -> None:
    entries = sorted(matches, key=lambda match: match["id"])
    body = ",\n  ".join(
        f'"{match["id"]}": {{ search: {json.dumps(match["guide_title"])}, page: {match["section"]} }}'
        for match in entries
    )
    ANCHORS_JS.write_text(
        "/** Auto-generated by scripts/add-pdf-anchors.py — do not edit by hand. */\n"
        f'const GAME_DETAIL_GUIDE = "./assets/Final_Board_Game_Report_V3.docx";\n'
        f"const GAME_PDF_ANCHORS = {{\n  {body}\n}};\n",
        encoding="utf-8",
    )


def main() -> int:
    if not DOCX_PATH.exists():
        print(f"Missing Word guide: {DOCX_PATH}", file=sys.stderr)
        return 1

    games = load_games()
    paragraphs = read_docx_paragraphs(DOCX_PATH)
    positions = find_guide_title_positions(paragraphs)
    matched, unmatched = match_games(games, positions)
    write_anchors_js(matched)

    report = {
        "guide": str(DOCX_PATH.relative_to(ROOT)),
        "sections_found": len({entry["section"] for entries in positions.values() for entry in entries}),
        "matched": len(matched),
        "unmatched": unmatched,
        "matches": matched,
    }
    REPORT_PATH.write_text(json.dumps(report, indent=2), encoding="utf-8")

    print(f"Guide section matches: {len(matched)}")
    print(f"No guide section: {len(unmatched)}")
    if unmatched:
        for item in unmatched:
            print(f"  - {item['id']}: {item['name']}")
    print(f"Wrote {ANCHORS_JS.relative_to(ROOT)}")
    print("Tip: also run python3 scripts/build-guide-html.py after editing the Word file.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
